from pathlib import Path

PATTERNS: dict[str, list[str]] = {
    "always": [
        ".git/", "*.log", ".DS_Store", "Thumbs.db",
        "*.png", "*.jpg", "*.jpeg", "*.gif", "*.pdf",
        "*.bin", "*.safetensors", "*.pt", "*.onnx",
    ],
    "python": [
        "**/__pycache__/**", "**/*.pyc", "**/*.pyo",
        "*.egg-info/", "dist/", "build/", ".venv/", "venv/",
        ".ruff_cache/", ".mypy_cache/", ".pytest_cache/",
    ],
    "node": [
        "node_modules/", ".next/", "dist/", ".nuxt/",
        "coverage/", "*.min.js", "*.min.css",
    ],
    "rust":    ["target/"],
    "go":      ["vendor/"],
    "generic": [],
}


def detect_project_types(root: Path) -> list[str]:
    types = []
    if (root / "pyproject.toml").exists() or (root / "setup.py").exists():
        types.append("python")
    if (root / "package.json").exists():
        types.append("node")
    if (root / "Cargo.toml").exists():
        types.append("rust")
    if (root / "go.mod").exists():
        types.append("go")
    return types or ["generic"]


class ClaudeignoreGenerator:
    def generate(self, root: Path) -> str:
        types = detect_project_types(root)
        lines = ["# Auto-generated by claude-efficient", ""]
        lines += PATTERNS["always"]
        for t in types:
            if t in PATTERNS:
                lines += ["", f"# {t}"] + PATTERNS[t]
        return "\n".join(lines)

    def write(self, root: Path, content: str) -> Path:
        out = root / ".claudeignore"
        out.write_text(content)
        (root / ".geminiignore").write_text(content)
        return out
