from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SUPPORTED_CLIS = ("gemini", "opencode", "cursor")
STATUS_VALUES = {"idle", "running", "error"}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _marker_path(cli_name: str, cwd: Path) -> Path:
    return cwd / f".ce-{cli_name}-session"


def _normalize_agent_name(value: str | None, fallback: str) -> str:
    candidate = (value or "").strip()
    return candidate or fallback


def _resolve_agent_name(
    requested: str | None,
    session_data: dict[str, Any] | None,
) -> str:
    from_request = _normalize_agent_name(requested, "")
    if from_request:
        return from_request

    from_env = _normalize_agent_name(os.environ.get("CE_AGENT_NAME"), "")
    if from_env:
        return from_env

    from_session = ""
    if session_data:
        from_session = _normalize_agent_name(str(session_data.get("agent_name", "")), "")
    if from_session:
        return from_session

    return "unassigned"


def _read_marker(marker: Path) -> dict[str, Any] | None:
    if not marker.exists():
        return None
    try:
        return json.loads(marker.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"status": "error", "last_error": "session marker is unreadable"}


def _write_marker(
    marker: Path,
    *,
    cli_name: str,
    cwd: Path,
    agent_name: str,
    status: str,
    pid: int | None = None,
    last_error: str | None = None,
) -> None:
    marker.write_text(
        json.dumps(
            {
                "cli": cli_name,
                "cwd": str(cwd),
                "agent_name": agent_name,
                "status": status,
                "pid": pid,
                "last_error": last_error,
                "updated_at": _now_iso(),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def _is_pid_running(pid: Any) -> bool:
    if not isinstance(pid, int) or pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def _spawn_process(command: list[str], cwd: Path, env: dict[str, str]) -> subprocess.Popen[str]:
    return subprocess.Popen(
        command,
        cwd=str(cwd),
        env=env,
        shell=(sys.platform == "win32"),
    )


def _build_run_command(cli_name: str, task: str, cwd: Path, agent_name: str) -> tuple[list[str] | None, str | None]:
    if cli_name == "gemini":
        return [
            "gemini",
            "--include-directories",
            str(cwd),
            "--approval-mode",
            "auto",
            "-p",
            task,
        ], None

    if cli_name == "opencode":
        return ["opencode", "run", task], None

    if cli_name == "cursor":
        cursor_binary = shutil.which("cursor")
        if not cursor_binary:
            return None, "Cursor CLI was not found on PATH."
        task_file = cwd / ".ce-cursor-task.md"
        task_file.write_text(
            "\n".join(
                [
                    f"# Cursor task for {agent_name}",
                    "",
                    task,
                    "",
                    "_Generated by ce-cursor as an interactive fallback._",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        return [cursor_binary, str(task_file)], None

    return None, f"Unsupported CLI '{cli_name}'."


def _run_init(cli_name: str, cwd: Path, agent_name: str) -> int:
    os.environ["CE_AGENT_NAME"] = agent_name
    marker = _marker_path(cli_name, cwd)
    _write_marker(
        marker,
        cli_name=cli_name,
        cwd=cwd,
        agent_name=agent_name,
        status="idle",
        pid=None,
        last_error=None,
    )
    return 0


def _run_status(cli_name: str, cwd: Path) -> int:
    marker = _marker_path(cli_name, cwd)
    data = _read_marker(marker)
    if not data:
        print("idle")
        return 0

    status = str(data.get("status", "idle")).lower()
    agent_name = _normalize_agent_name(str(data.get("agent_name", "")), "unassigned")
    last_error = data.get("last_error")

    if status == "running":
        pid = data.get("pid")
        if _is_pid_running(pid):
            print("running")
            return 0
        status = "error" if last_error else "idle"
        _write_marker(
            marker,
            cli_name=cli_name,
            cwd=cwd,
            agent_name=agent_name,
            status=status,
            pid=None,
            last_error=last_error if status == "error" else None,
        )

    if status not in STATUS_VALUES:
        status = "error"

    print(status)
    return 1 if status == "error" else 0


def _run_task(cli_name: str, cwd: Path, agent_name: str, task: str) -> int:
    import time
    from datetime import datetime
    from claude_efficient.prompt.optimizer import optimize
    from claude_efficient.analysis.telemetry import TelemetryRecord, record as tel_record

    start_time = time.time()
    
    opt = optimize(task)
    optimized_task = opt.text if opt.text else task

    marker = _marker_path(cli_name, cwd)
    command, error = _build_run_command(cli_name, optimized_task, cwd, agent_name)
    if error:
        _write_marker(
            marker,
            cli_name=cli_name,
            cwd=cwd,
            agent_name=agent_name,
            status="error",
            pid=None,
            last_error=error,
        )
        print(error, file=sys.stderr)
        return 1

    env = os.environ.copy()
    env["CE_AGENT_NAME"] = agent_name
    try:
        process = _spawn_process(command, cwd, env)
        _write_marker(
            marker,
            cli_name=cli_name,
            cwd=cwd,
            agent_name=agent_name,
            status="running",
            pid=process.pid,
            last_error=None,
        )
        exit_code = process.wait()
    except OSError as exc:
        message = str(exc)
        _write_marker(
            marker,
            cli_name=cli_name,
            cwd=cwd,
            agent_name=agent_name,
            status="error",
            pid=None,
            last_error=message,
        )
        print(message, file=sys.stderr)
        return 1

    duration = time.time() - start_time
    rec = TelemetryRecord(
        timestamp=datetime.now().isoformat(timespec="seconds"),
        mode="pipe",
        model=cli_name,
        prompt_chars_original=len(task),
        prompt_chars_optimized=len(optimized_task),
        chars_saved=opt.chars_saved,
        session_duration_s=round(duration, 2),
    )
    tel_record(cwd, rec)

    if exit_code == 0:
        _write_marker(
            marker,
            cli_name=cli_name,
            cwd=cwd,
            agent_name=agent_name,
            status="idle",
            pid=None,
            last_error=None,
        )
    else:
        _write_marker(
            marker,
            cli_name=cli_name,
            cwd=cwd,
            agent_name=agent_name,
            status="error",
            pid=None,
            last_error=f"process exited with code {exit_code}",
        )
    return exit_code


def run_wrapper_command(
    cli_name: str,
    command: str,
    *,
    task: str | None = None,
    agent_name: str | None = None,
    cwd: str | Path | None = None,
) -> int:
    normalized_cli = (cli_name or "").strip().lower()
    normalized_command = (command or "").strip().lower()
    if normalized_cli not in SUPPORTED_CLIS:
        print(f"Unsupported CLI '{cli_name}'.", file=sys.stderr)
        return 2
    if normalized_command not in {"init", "run", "status"}:
        print(f"Unsupported command '{command}'.", file=sys.stderr)
        return 2

    current_dir = Path(cwd or os.getcwd()).resolve()
    marker = _marker_path(normalized_cli, current_dir)
    session_data = _read_marker(marker)
    resolved_agent = _resolve_agent_name(agent_name, session_data)

    if normalized_command == "init":
        return _run_init(normalized_cli, current_dir, resolved_agent)

    if normalized_command == "status":
        return _run_status(normalized_cli, current_dir)

    task_text = (task or "").strip()
    if not task_text:
        print("run requires a non-empty task.", file=sys.stderr)
        return 2

    if not marker.exists():
        _run_init(normalized_cli, current_dir, resolved_agent)
    return _run_task(normalized_cli, current_dir, resolved_agent, task_text)


def wrapper_main(cli_name: str, argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog=f"ce-{cli_name}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init")
    init_parser.add_argument("--agent-name", dest="agent_name", default=None)

    run_parser = subparsers.add_parser("run")
    run_parser.add_argument("task", nargs="+")
    run_parser.add_argument("--agent-name", dest="agent_name", default=None)

    subparsers.add_parser("status")

    args = parser.parse_args(argv)
    command = args.command
    agent_name = getattr(args, "agent_name", None)
    task_text = None
    if command == "run":
        task_text = " ".join(args.task).strip()

    return run_wrapper_command(
        cli_name,
        command,
        task=task_text,
        agent_name=agent_name,
    )


def router_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ce-router")
    parser.add_argument("--cli", choices=SUPPORTED_CLIS, required=True)
    parser.add_argument("--cmd", choices=("init", "run", "status"), required=True)
    parser.add_argument("--agent-name", dest="agent_name", default=None)
    parser.add_argument("--task", default=None)
    parser.add_argument("task_parts", nargs="*")
    args = parser.parse_args(argv)

    task_text = args.task
    if args.cmd == "run" and not task_text:
        task_text = " ".join(args.task_parts).strip()

    return run_wrapper_command(
        args.cli,
        args.cmd,
        task=task_text,
        agent_name=args.agent_name,
    )
